import {
  UserProfile,
  TodayJourney,
  ActiveExperiment,
  WisdomQuote,
  CognitiveDistortionStat,
  RecentInsight,
  BadgeItem,
} from './types';

export const initialUserProfile: UserProfile = {
  name: 'Alex',
  title: 'Cognitive Mastery Practitioner',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  level: 12,
  totalXp: 2450,
  currentStreakDays: 7,
  sessionsCompletedCount: 12,
  experimentsCompletedCount: 12,
  proActive: true,
};

export const initialTodayJourney: TodayJourney = {
  thoughtCaptured: true,
  cbtReflection: false,
  todaysMission: false,
  eveningReflection: false,
};

export const initialActiveExperiment: ActiveExperiment = {
  id: 'exp-1',
  title: 'Exposure Task',
  status: 'Active',
  description: 'Overcoming hesitation in professional outreach.',
  task: 'Apply to one company today',
  completed: false,
  endsInHours: 4,
  xpReward: 100,
};

export const initialCognitivePatterns: CognitiveDistortionStat[] = [
  {
    name: 'Catastrophizing',
    percentage: 40,
    color: 'bg-emerald-900',
    description: 'Expecting worst-case scenarios without factual basis.',
  },
  {
    name: 'Perfectionism',
    percentage: 30,
    color: 'bg-emerald-800',
    description: 'Demanding flawless execution before taking action.',
  },
  {
    name: 'All-or-Nothing',
    percentage: 15,
    color: 'bg-emerald-700',
    description: 'Viewing outcomes in absolute black-or-white terms.',
  },
  {
    name: 'Mind Reading',
    percentage: 10,
    color: 'bg-emerald-600',
    description: 'Assuming others think negatively about you without proof.',
  },
];

export const initialRecentInsights: RecentInsight[] = [
  {
    id: 'ins-1',
    title: 'Anxiety reduction trending',
    subtitle: 'Your evening clarity sessions are 15% more effective.',
    iconType: 'trend',
    fullContent:
      'Statistical review of your last 10 evening reflection logs demonstrates a 15% improvement in cognitive clarity score when sessions are logged before 9:00 PM.',
    date: 'Just now',
  },
  {
    id: 'ins-2',
    title: 'New Cognitive Tool Unlocked',
    subtitle: 'Decatastrophizing Matrix is now in your toolkit.',
    iconType: 'brain',
    fullContent:
      'The Decatastrophizing Matrix helps dissect catastrophic expectations into "Best Case", "Worst Case", and "Most Likely Case", drastically reducing physiological cortisol spikes.',
    date: 'Just now',
  },
];

export const initialWisdomQuotes: WisdomQuote[] = [
  {
    id: 'w-nietzsche',
    quote: 'He who has a why to live can bear almost any how.',
    author: 'Friedrich Nietzsche',
    source: "Man's Search for Meaning Context",
    tradition: 'Existentialism',
    theme: 'Purpose & Meaning',
    insight: 'Finding intrinsic purpose transforms daunting challenges into meaningful endeavors.',
    practicalApplication: 'When feeling unmotivated, write down why this step matters to your long-term values.',
    isInsightOfDay: true,
    unlocked: true,
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    isFavorite: true,
  },
  {
    id: 'w-epictetus',
    quote: 'You have control over your actions, not the outcome.',
    author: 'Epictetus',
    source: 'The Enchiridion',
    tradition: 'Stoicism',
    theme: 'Dichotomy of Control',
    insight: 'Anxiety stems from attempting to dictate external results rather than mastering internal intent.',
    unlocked: true,
    isFavorite: true,
  },
  {
    id: 'w-krishna',
    quote: 'The mind is restless and difficult to restrain, but it is subdued by practice.',
    author: 'Lord Krishna',
    source: 'Bhagavad Gita',
    tradition: 'Indian Philosophy',
    theme: 'Disciplined Mind',
    insight: 'Cognitive reframing is a muscle. Habitual repetition gradually builds mental resilience.',
    unlocked: true,
  },
  {
    id: 'w-laotzu',
    quote: 'Nature does not hurry, yet everything is accomplished.',
    author: 'Lao Tzu',
    source: 'Tao Te Ching',
    tradition: 'Taoism',
    theme: 'Flow & Patience',
    insight: 'Urgency is often an illusion generated by perfectionist anxiety. Steady effort produces lasting growth.',
    unlocked: true,
  },
  {
    id: 'w-dalai',
    quote: 'Happiness is not something ready made. It comes from your own actions.',
    author: 'Dalai Lama',
    source: 'Buddhism • Self-Agency',
    tradition: 'Buddhism',
    theme: 'Self-Agency',
    insight: 'Mindfulness requires active participation and conscious reframing rather than passive waiting.',
    unlocked: true,
  },
  {
    id: 'w-seneca',
    quote: 'We suffer more often in imagination than in reality.',
    author: 'Seneca',
    source: 'Stoicism • Anxiety Relief',
    tradition: 'Stoicism',
    theme: 'Anxiety Relief',
    insight: 'Anticipatory fear exaggerates hardship. Ground yourself in present evidence.',
    unlocked: true,
  },
  {
    id: 'w-gita2',
    quote: "You have a right to your actions, but never to your action's fruits.",
    author: 'The Bhagavad Gita',
    source: 'Indian Philosophy • Detachment',
    tradition: 'Indian Philosophy',
    theme: 'Detachment',
    insight: 'Release attachment to expectations to eliminate fear of failure.',
    unlocked: true,
  },
  {
    id: 'w-laotzu2',
    quote: 'The journey of a thousand miles begins with a single step.',
    author: 'Lao Tzu',
    source: 'Taoism • Momentum',
    tradition: 'Taoism',
    theme: 'Momentum',
    insight: 'Break monumental goals into tiny, non-threatening daily micro-tasks.',
    unlocked: true,
  },
  {
    id: 'w-upcoming',
    quote: 'Upcoming Wisdom - Complete "Cognitive Reframing III" session to unlock this insight.',
    author: 'Philosophical Vault',
    source: 'MindDojo Mastery',
    tradition: 'Stoicism',
    unlocked: false,
  },
];

export const initialBadges: BadgeItem[] = [
  {
    id: 'b-1',
    name: 'First Reflection',
    icon: 'sparkles',
    description: 'Completed your first interactive CBT thought reframing session.',
    earnedDate: 'Just now',
    unlocked: true,
  },
  {
    id: 'b-2',
    name: '7-Day Streak',
    icon: 'flame',
    description: 'Logged mind reflections continuously for 7 consecutive days.',
    earnedDate: 'Just now',
    unlocked: true,
  },
  {
    id: 'b-3',
    name: 'Thought Hunter',
    icon: 'brain',
    description: 'Identified and cataloged over 10 distinct cognitive distortions.',
    earnedDate: 'Just now',
    unlocked: true,
  },
  {
    id: 'b-4',
    name: 'Stoic Mind',
    icon: 'compass',
    description: 'Applied 5 Stoic reframing principles to high-stress situations.',
    earnedDate: 'Just now',
    unlocked: true,
  },
  {
    id: 'b-5',
    name: 'Mission Master',
    icon: 'target',
    description: 'Successfully completed 10 exposure tasks and experiments.',
    earnedDate: 'Just now',
    unlocked: true,
  },
  {
    id: 'b-6',
    name: 'Decatastrophizer',
    icon: 'shield',
    description: 'Reframed a catastrophic thought with >80% emotion reduction.',
    earnedDate: 'Just now',
    unlocked: true,
  },
];

